apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-demo
  namespace: demo-aks-ariel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-readonly
  namespace: demo-aks-ariel
rules:
  # Core API group ("") resources
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]

  # apps/v1 resources
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-readonly-binding
  namespace: demo-aks-ariel
subjects:
  - kind: ServiceAccount
    name: sa-demo
    namespace: demo-aks-ariel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-readonly
