apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
  namespace: demo-aks-ariel
spec:
  selector:
    app: nginx-deployment
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer